function createfigure1(Y1)
%CREATEFIGURE1(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 14-Aug-2015 23:57:00

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[20 50]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(Y1);

% Create title
title('Average Spiking Time with Increasing Current');

% Create xlabel
xlabel('Neuron Number (k)');

% Create ylabel
ylabel('Average Time (ms)');

