function createfigureCurrents(X1, Y1, Y2, Y3, Title)
%CREATEFIGURE(X1, Y1, Y2, Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 11-Oct-2015 23:18:11

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(5,1,1,'Parent',figure1);
box(subplot1,'on');
hold(subplot1,'all');

% Create plot
plot(X1,Y1,'Parent',subplot1);

% Create ylabel
ylabel('Neuron 1');

% Create title
title(Title);

% Create subplot
subplot2 = subplot(5,1,2,'Parent',figure1);
box(subplot2,'on');
hold(subplot2,'all');

% Create plot
plot(X1,Y2,'Parent',subplot2);

% Create ylabel
ylabel('Neuron 2');

% Create subplot
subplot3 = subplot(5,1,3,'Parent',figure1);
box(subplot3,'on');
hold(subplot3,'all');

% Create plot
plot(X1,Y2,'Parent',subplot3);

% Create ylabel
ylabel('Neuron 3');

% Create subplot
subplot4 = subplot(5,1,4,'Parent',figure1);
box(subplot4,'on');
hold(subplot4,'all');

% Create plot
plot(X1,Y2,'Parent',subplot4);

% Create ylabel
ylabel('Neuron 4');

% Create subplot
subplot5 = subplot(5,1,5,'Parent',figure1);
box(subplot5,'on');
hold(subplot5,'all');

% Create plot
plot(X1,Y3,'Parent',subplot5);

% Create xlabel
xlabel('Time (s)');

% Create ylabel
ylabel('Neuron 5');

