function createfigureSpikes(xvector1, yvector1, yvector2, yvector3, Title)
%CREATEFIGURE(XVECTOR1, YVECTOR1, YVECTOR2, YVECTOR3)
%  XVECTOR1:  bar xvector
%  YVECTOR1:  bar yvector
%  YVECTOR2:  bar yvector
%  YVECTOR3:  bar yvector

%  Auto-generated by MATLAB on 11-Oct-2015 23:14:37

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(5,1,1,'Parent',figure1);
box(subplot1,'on');
hold(subplot1,'all');

% Create bar
bar(xvector1,yvector1,'EdgeColor','flat','Parent',subplot1);

% Create ylabel
ylabel('Neuron 1');

% Create title
title(Title);

% Create subplot
subplot2 = subplot(5,1,2,'Parent',figure1);
box(subplot2,'on');
hold(subplot2,'all');

% Create bar
bar(xvector1,yvector2,'EdgeColor','flat','Parent',subplot2);

% Create ylabel
ylabel('Neuron 2');

% Create subplot
subplot3 = subplot(5,1,3,'Parent',figure1);
box(subplot3,'on');
hold(subplot3,'all');

% Create bar
bar(xvector1,yvector2,'EdgeColor','flat','Parent',subplot3);

% Create ylabel
ylabel('Neuron 3');

% Create subplot
subplot4 = subplot(5,1,4,'Parent',figure1);
box(subplot4,'on');
hold(subplot4,'all');

% Create bar
bar(xvector1,yvector2,'EdgeColor','flat','Parent',subplot4);

% Create ylabel
ylabel('Neuron 4');

% Create subplot
subplot5 = subplot(5,1,5,'Parent',figure1);
box(subplot5,'on');
hold(subplot5,'all');

% Create bar
bar(xvector1,yvector3,'EdgeColor','flat','Parent',subplot5);

% Create xlabel
xlabel('Time (s)');

% Create ylabel
ylabel('Neuron 5');

