function createfigure(X1, Y1, Y2)
%CREATEFIGURE(X1, Y1, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 18-Sep-2015 02:35:29

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.129267935578331 0.583837209302326 0.775 0.341162790697675]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1);

% Create title
title('{w}_{o} = 250, {\sigma}_{w} = 25');

% Create ylabel
ylabel('Post-Synaptic Current Summation (A)');

% Create subplot
subplot1 = subplot(2,1,2,'Parent',figure1);
box(subplot1,'on');
hold(subplot1,'all');

% Create plot
plot(X1,Y2,'Parent',subplot1);

% Create xlabel
xlabel('Time (ms)');

% Create ylabel
ylabel('Post-Synaptic Membrane Potential (V)');

