function createfigure(X1, Y1, Y2)
%CREATEFIGURE(X1, Y1, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 18-Sep-2015 02:27:37

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1);
box(subplot1,'on');
hold(subplot1,'all');

% Create plot
plot(X1,Y1,'Parent',subplot1);

% Create ylabel
ylabel('Post-Synaptic Current Summation (A)');

% Create title
title('w_{o} = 50, {\sigma}_{w} = 5');

% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1);
box(subplot2,'on');
hold(subplot2,'all');

% Create plot
plot(X1,Y2,'Parent',subplot2);

% Create xlabel
xlabel('Time (ms)');

% Create ylabel
ylabel('Post-Synaptic Potential (V)');

