function createfigureWeights(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 18-Sep-2015 05:38:35

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'Color',[1 0 0],'DisplayName','Before');
set(plot1(2),'Color',[0 1 0],'DisplayName','After');

% Create title
title('Synaptic Weights - Before and After Training');

% Create xlabel
xlabel('Synapse Number');

% Create ylabel
ylabel('Synaptic Weight');

% Create legend
legend(axes1,'show');

